accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from accounts.views import sign_up

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", sign_up, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import (
    ProjectsListView,
    ProjectDetailView,
    NewProjectCreateView,
)


urlpatterns = [
    path("", ProjectsListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", NewProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import TaskCreateView, TaskListView, TaskUpdateView


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        "auth.User", null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

tasks/forms.py
from django.forms.widgets import DateInput
from django.forms import ModelForm
from .models import Task


class DateInput(DateInput):
    input_type = "date"


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["name", "start_date", "due_date", "project", "assignee"]
        widgets = {
            "start_date": DateInput(attrs={"type": "date"}),
            "due_date": DateInput(attrs={"type": "date"}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


def sign_up(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

projects/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from projects.models import Project


class ProjectsListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class NewProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    fields = ["name", "description", "members"]
    template_name = "projects/new.html"

    def get_success_url(self):
        return reverse_lazy("show_project", kwargs={"pk": self.object.pk})

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from tasks.models import Task
from tasks.forms import TaskForm


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    # fields = ["name", "start_date", "due_date", "project", "assignee"]
    template_name = "tasks/new.html"
    form_class = TaskForm

    def get_success_url(self):
        return reverse_lazy(
            "show_project", kwargs={"pk": self.object.project.id}
        )


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


# 1st try
class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'css/images/favicon.ico' %}" />
    <title>Projects{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
</head>

<body>
    <header>
        <nav role="navigation">
            <div id="menuToggle">
                <input name="toggle" type="checkbox" />
                <label for="toggle">
                    <span>menu</span>
                    <div></div>
                    <div></div>
                    <div></div>
                </label>
                <ul id="menu">
                    {% if user.is_authenticated %}
                    <a href="{% url 'list_projects' %}">
                        <li>My projects</li>
                    </a>
                    <a href="{% url 'create_project' %}">
                        <li>Create new project</li>
                    </a>
                    <a href="{% url 'show_my_tasks' %}">
                        <li>My tasks</li>
                    </a>
                    <a href="{% url 'create_task' %}">
                        <li>Add tasks</li>
                    </a>
                    <a href="{% url 'logout' %}">
                        <li>Logout</li>
                    </a>
                    {% else %}
                    <a href="{% url 'login' %}">
                        <li>Login</li>
                    </a>
                    <a href="{% url 'signup' %}">
                        <li>Signup</li>
                    </a>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    {% block main %}
    {% endblock main %}
</body>

</html>

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block title %} Detials {% endblock title %}

{% block main %}
    <main class="project-center">
        <div>
            <div class="title-card-grid">
                <div>
                    <h1 class="project-title">{{ project.name }}</h1>
                </div>
                <div>
                    <h1>
                        <a href="{% url 'list_projects'%}">
                            <div class="tooltip">x
                                <span class="tooltiptext">Back to your projects</span>
                            </div>
                        </a>
                    </h1>
                </div>
            </div>
            <h2>Description:</h2>
            <p>{{ project.description|markdownify }}</p>
            <div class="task-center">
                <div class="task-card-grid">
                    <div class="task-link">
                        <h2>
                            <a href="{% url 'show_my_tasks' %}">
                                <div class="tooltip">Tasks
                                    <span class="tooltiptext">Go to My Tasks</span>
                                </div> 
                            </a>
                        </h2>
                    </div>
                    <div>
                        <h2>
                            <a href="{% url 'create_task' %}">
                                <div class="tooltip">+
                                    <span class="tooltiptext">Add a new Task</span>
                                </div>
                            </a>
                        </h2>
                    </div>
                </div>
                {% if project.tasks.all|length > 0 %}
                    <table class="task-detail-table">
                        <thead>
                            <tr>
                                <th>Task Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for task in project.tasks.all %}
                                <tr>
                                    <td>{{ task.name }}</td>
                                    <td>{{ task.assignee }}</td>
                                    <td>{{ task.start_date|date:"D, M d, Y" }}</td>
                                    <td>{{ task.due_date|date:"D, M d, Y"  }}</td>
                                    <td>{% if task.is_completed == True %} yes {% else %} no {% endif %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>This project has no tasks</p>
                {% endif %}
            </div>
        </div>
    </main>

{% endblock main %}

projects/templates/projects/list.html
{% extends 'base.html' %}

{% block title %} list {% endblock title %}

{% block main %}
    <main class="project-center">
        <div>
            <div class="title-card-grid">
                <div>
                <h1>My Projects</h1>
                </div>
                <div>
                    <h1>
                        <a href="{% url 'create_project'%}">
                            <div class="tooltip">+
                                <span class="tooltiptext">Add a new Project</span>
                            </div>
                        </a>
                    </h1>
                </div>
            </div>
            {% if user.projects.all|length == 0 %}
                <p>You are not assigned to any projects</p>
            {% endif %}
            <table class="list-table">
                <thead>
                    {% if user.projects.all|length > 0%}
                        <tr>
                            <th>Project Name</th>
                            <th>Number of tasks</th>
                        </tr>
                    {% endif %}
                </thead>
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td><a href="{% url 'show_project' project.pk%}">{{ project.name }}</a></td>
                            <td>{{ project.tasks.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock main %}

projects/templates/projects/new.html
{% extends 'base.html' %}

{% block title %}- Create New {% endblock title %}

{% block main%}

    <main class="project-center">
        <div>
            <div class="title-card-grid">
                <div>
                    <h1>Create a new project</h1>
                </div>
                <div>
                    <h1>
                        <a href="{% url 'list_projects'%}">
                            <div class="tooltip">x
                                <span class="tooltiptext">Cancel</span>
                            </div>
                        </a>
                    </h1>
                </div>
            </div>
            <div class="project-form">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-button">
                        <button>Create</button>
                    </div>
                </form>
            </div>
        </div>
    </main>

{% endblock main %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}

{% block title %}- Your Tasks {% endblock title %}

{% block main %}
    <main class="project-center">
        <div>
            <div class="title-card-grid">
                <div>
                    <h1 class="project-title">My Tasks</h1>
                </div>
                <div>
                    <h1>
                        <a href="{% url 'list_projects'%}">
                            <div class="tooltip">x
                                <span class="tooltiptext">Close</span>
                            </div>
                        </a>
                    </h1>
                </div>
            </div>
            {% if task_list.all|length > 0 %}
                <table class="detail-table">
                    <thead>
                        <tr>
                            <th>Project</th>
                            <th>Task</th>
                            <th>Start date</th>
                            <th>End date</th>
                            <th>Is completed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td><a href="{% url 'show_project' task.project.pk%}">{{ task.project.name }}</a></td>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date|date }}</td>
                                <td>{{ task.due_date|date }}</td>
                                {% if task.is_completed == True %}
                                    <td>Done</td>
                                {% else %}
                                    <td>
                                        <form method="post" action="{% url 'complete_task' task.id %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="is_completed" value="True"/>
                                            <button>Complete</button>
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock main %}

tasks/templates/tasks/new.html
{% extends "base.html" %}

{%block title%}- Create New Task
{%endblock title%}

{% block main %}
    <main class="project-center">
        <div>
            <div class="title-card-grid">
                <div>
                    <h1 class="project-title">Create a new task</h1>
                </div>
                <div>
                    <h1>
                        <a href="{% url 'show_my_tasks'%}">
                            <div class="tooltip">x
                                <span class="tooltiptext">Cancel</span>
                            </div>
                        </a>
                    </h1>
                </div>
            </div>
            <div class="task-form">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-button">
                        <button type="submit">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock main %}